apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freeflix
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Replace with your GitHub / Git repository URL
    repoURL: https://github.com/LakshanWMRT/freeflix.git
    targetRevision: main
    path: k8s
  destination:
    # Points to local k3s cluster where ArgoCD is installed
    server: https://kubernetes.default.svc
    namespace: freeflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
